### ISSUE TITLE
Formulaire "informations commande"

### ISSUE THREAD

**Issue by v-bl** [clem4net/JaponSuki-Support#1]
Absence de vérification du contenu téléphone. 
Exemple : chaine de caractère validée dans le numéro de téléphone.

En mode visiteur, j'ai validé mon panier puis je suis redirigé vers Stancer. Sur mon navigateur je décide de retourner sur le japon-suki sans valider le paiement.
Je perds le contenu de mon panier et le stock global est impacté pour tous les utilisateurs.
Si absence de stock, le produit est toujours disponible sur le site :
<img width="310" alt="stock" src="https://github.com/clem4net/JaponSuki-Support/assets/174019594/a5c1c54d-5ffa-4cd3-a711-54e9779b4569">

**Comment by v-bl** [comment]
Ok pour le fonctionnement.
Par contre, pourquoi le stock global des articles est impacté par un panier qui apparait vide ?
C'est visible car peu de stock mais ça ne peut pas être problématique ?

**Comment by v-bl** [comment]
Je rebondis sur ma problématique, qui est la suivante.
L'accès au détail des commandes n'est pas assez visible. Je suis passé à côté hier et c'est seulement ce matin que j'ai découvert ce pan.
Je suis sur navigateur desktop : 
![image](https://github.com/clem4net/JaponSuki-Support/assets/174019594/87a9a3e1-1fd2-4988-bbe9-348ff0e4e7e6)

Je n'ai pas vu que depuis "mon espace" on pouvait avoir accès à un ensemble de lien dont "Suivi des commandes".
De mon point de vu, il faudrait mettre un lien sur l'historique des commandes dans la partie panier.

Bonne journée !

**Comment by clem4net** [comment]
Vincent, merci pour tes différents retours :)

 - Vérification du téléphone
 => pris en compte
 
 - Retour en arrière sur le paiement
 + Pour Stancer, c'est pas top mais j'ai changé le comportement.
     Si on fait retour arrière, ca revient forcément sur le paiement (sauf si tu t'excites sur le bouton arrière ...)
 + Pour Paypal, ca recharge la commande et du peut la modifier
 => Dans tous les cas, un lancement de paiement revient à transformer le panier en commande
 
... donc pour le stock global  :
 Une fois le paiement lancé, les articles sont réservés pour éviter de vendre 2 fois la même chose.
 Si une commande reste dans un état "bloqué" (paiement en erreur), un message est envoyé 48h après pour rappeler au client qu'il doit finaliser sa commande.
 => 24h après, si la commande n'est pas finie, elle est annulée et le stock revient
 
  - Visibilité du suivi des commandes
  => J'ai ajouté un bouton en plus de 'allez à la boutique"

**Comment by clem4net** [comment]
Correction : le panier est vidé dès la création de la commande

Les actions sont dans l'ordre :
 - enregistrement de la commande
 - suppression du panier
 - création du paiement
 -
