### ISSUE TITLE
Les offres

### ISSUE THREAD

**Issue by v-bl** [clem4net/JaponSuki-Support#11]
On ne peut plus ajouter ou éditer "les options" des offres. Les changements ne sont pas enregistrés.

![image](https://github.com/user-attachments/assets/09f17fe6-7dfa-48f8-a509-e2ad1bc27e6f)

**Comment by clem4net** [comment]
Peut-être qu'il y a une incompréhension sur le fonctionnement.
Je viens de tester sur l'offre cuisine et ca fonctionne.

Après ajout / modification d'une option, il faut forcément cliquer sur "enregistrer" en haut.
Est-ce que c'est ça qui tu ne fais pas ? ou il y a un vrai autre problème ?

**Comment by v-bl** [comment]
Effectivement je n'enregistrai pas l'offre : ça fonctionne.
Peut être, une fois l'offre créée, rattacher les options à chaque validation de la modale ?

Autre point, sur le formulaire de l'option : la date est obligatoire mais si je renseigne autre chose qu'une date, l'option est ajoutée.
A l'enregistrement de l'offre : 
![image](https://github.com/user-attachments/assets/bd33d262-e0b6-4d65-8be4-3a5f95b2cb05)

Il faudrait un contrôle sur le format de la date.

**Comment by clem4net** [comment]
Retours pris en compte et déployés.
