### ISSUE TITLE
Les membres

### ISSUE THREAD

**Issue by v-bl** [clem4net/JaponSuki-Support#13]
Le titre de la colonne est : Adhérant 01-0001 - 01-0001
![image](https://github.com/user-attachments/assets/633c20ee-31eb-417c-bfbe-2200ea721f6e)

Je ne pense pas que ce soit une anomalie mais je ne comprends pas comment affecter le membre à la période. J'ai adhéré à la période.

De plus la balance est négative elle ne devrait pas être à 0 ? L'activité a été payée.

**Comment by clem4net** [comment]
Il n'y a aucune période active à aujourd'hui.
La seule période existante est du 02/09/2024 au 01/10/2025 = le 07/08/2024 n'est pas dans le range
 - L'entête de la colonne affiche la période courante (mais il n'y en a pas, d'om le 01-01)
 - La liste affiche l'info de l'adhésion
=> Ce sont 2 informations distinctes, il y a une incohérence

Sur la balance, je suis d'accord.
Cette info est un peu compliquée à calculer car elle prend en compte toutes les périodes.
Comme aucune période n'est "courante", cela a peut-être généré un problème.

Il faut que je regarde ces 2 points.

**Comment by clem4net** [comment]
Corrigé / Déployé

J'avais oublié de mettre à jour la balance du membre ..
Pour le reste, j'ai revue complètement la colonne :
 - Elle affiche la période de dernière adhésion du membre
 - J'ai ajouté un paginator
