### ISSUE TITLE
Page : Mes inscriptions

### ISSUE THREAD

**Issue by v-bl** [clem4net/JaponSuki-Support#14]
Problème d'affichage du filtre :période 
![image](https://github.com/user-attachments/assets/f21c1225-6eed-40bf-bd03-ba59858ad834)

A l'initialisation de la page lorsqu'aucun filtre actif.

**Comment by v-bl** [comment]
Lorsque je clique sur "nouvelle inscription" j'ai une erreur (toastr) et la période est non initialisée : 
![image](https://github.com/user-attachments/assets/9da83673-6f38-42c7-986a-098f1941bbdb)

**Comment by clem4net** [comment]
Corrigé / Déployé

Sur le filtre de période, c'est corrigé
Sur l'inscription, c'est une erreur fonctionnelle : il n'y a pas de période active, il n'est pas possible de s'inscire
