### ISSUE TITLE
[Object object] dans les cartes Mapbox en bas d'articles

### ISSUE THREAD

**Issue by tpetillon** [clem4net/JaponSuki-Support#4]
Affiché pendant quelques secondes une fois que la carte est chargée :

![image](https://github.com/clem4net/JaponSuki-Support/assets/204831/00b0137d-5a3c-4790-a373-a696b1794e2b)

**Comment by clem4net** [comment]
J'ai eu du mal à reproduire car je teste toujours en étant connecté à mon site.
L'API appelée plante en anonyme uniquement => elle est sécurisé alors qu'elle ne devrait pas.

Merci, je corrige ca :)

**Comment by clem4net** [comment]
MEP faite, correction OK !
