### ISSUE TITLE
Tags non cliquables

### ISSUE THREAD

**Issue by tpetillon** [clem4net/JaponSuki-Support#5]
On s'attend à pouvoir cliquer sur ces tags pour voir tous les articles ainsi taggués :

![image](https://github.com/clem4net/JaponSuki-Support/assets/204831/d4047ca5-9da0-4937-acff-971a0489ea09)

Et du coup, une page pour voir tous les tags et aller voir les articles correspondants serait pas mal aussi.

**Comment by clem4net** [comment]
Bien vu, c'est pour cela qu'ils sont cachés tout en bas pour l'instant XD

**Comment by clem4net** [comment]
Les tags sont gérés comme des catégories 
Ils sont maintenant cliquables et ouvrent la catégorie associée.
