### ISSUE TITLE
Administration - Présentation publique (maj)

### ISSUE THREAD

**Issue by v-bl** [clem4net/JaponSuki-Support#6]
Sur cet écran, lorsque j'enregistre, j'ai un bref toastr en erreur qui s'affiche juste avant celui qui est vert.
![image](https://github.com/user-attachments/assets/a525008c-f78d-4d44-bbd7-a490152807d7)

Retour du put en cause : 
![image](https://github.com/user-attachments/assets/9774b148-0fb1-435b-8abb-34a82e03be47)

**Comment by clem4net** [comment]
Oui, j'ai vu le problème avec l'adresse en testant d'autres trucs.
=> J'ai apporté une correction, ce sera dans la v4.2

**Comment by clem4net** [comment]
Corrigé
