### ISSUE TITLE
Questions/remarques  autour de l'administration

### ISSUE THREAD

**Issue by v-bl** [clem4net/JaponSuki-Support#7]
1 - Comment ajouter une photo de présentation lors de l'édition de son asso ?
2 - L''image chargée dans l'article ne s'affiche pas. Lors du chargement d'une image d'un article, je trouve que l'information affichée "blob:https://www.japon-suki.fr/823575a5-d7ac-4e93-a57b-dded83e22273" n'est pas utile

**Comment by clem4net** [comment]
1 - C'est une fonctionnalité manquante ... => à faire
2 - L'appli n'avait pas le droit d'écrire les images sur le serveur => ce point est résolu

**Comment by clem4net** [comment]
Corrigé
