### ISSUE TITLE
Administration - Les adhésions

### ISSUE THREAD

**Issue by v-bl** [clem4net/JaponSuki-Support#8]
Lors de l'ajout d'une offre j'ai cette erreur : 
![image](https://github.com/user-attachments/assets/d321e730-e72c-4db8-887d-6d21039c130a)

Aucune offre n'est créée.

**Comment by v-bl** [comment]
Je n'arrive pas à reproduire cette erreur... Ca fonctionne.

**Comment by clem4net** [comment]
J'ai déjà eu ca mais pareil, non reproduit après.
=> J'avais fait une "pseudo correction" c'est toujours là

Je pense que le problème vient de la période qui n'est vue comme sélectionnée.
Dans le localstorage, je sauvegarde la dernière période sélectionnée pour que ce soit toujours celle sélectionnée quand on change de page

**Comment by clem4net** [comment]
Corrigé
